// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;
using Foundation;
using ObjCRuntime;
using static WBid.WBidMac.Mac.WindowControllers.UserAccoutDifference.UserAccountDifferenceController;

namespace WBid.WBidMac.Mac
{
	public partial class AccountCell : NSTableCellView
	{
		public UserAccountDiffTableSource Objsource;
		public AccountCell (NativeHandle handle) : base (handle)
		{
		}
		public override void AwakeFromNib()
		{
			base.AwakeFromNib();
			
		}
		public void BindData( string title,string localData,string serverData)
		{
			parameter.StringValue = title;
			parameterSegment.SelectedSegment = 0;
			parameterSegment.SetLabel(localData, 0);
			parameterSegment.SetLabel(serverData, 1);


		}
	}
}
