// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace WBid.WBidMac.Mac
{
	public partial class NewBidView : NSView
	{
		public NewBidView (IntPtr handle) : base (handle)
		{
		}
	}
}
